### ISSUE TITLE
Cloudflare相关部署配置

### ISSUE THREAD

**Issue by wjy2018** [wjy2018/hugoblogtalks#6]
https://blog.lastfantasy.top/p/cloudflare%E7%9B%B8%E5%85%B3%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE/?t=1734158570148 

 主要记录在Cloudflare相关部署过程遇到的问题和解决方法

**Comment by wjy2018** [comment]
第一次点进来之后没有gitalk评论模块，报错如下：
```txt
VM347:10  Uncaught ReferenceError: Gitalk is not defined  
    at <anonymous>:10:24  
    at <anonymous>:21:7  
    at module.exports (pjax.min.js:1:7651)
    at pjax.min.js:1:9113
    at NodeList.forEach (<anonymous>)
    at module.exports (pjax.min.js:1:9364)
    at module.exports (pjax.min.js:1:8931)
    at pjax.min.js:1:4649
    at NodeList.forEach (<anonymous>)
    at module.exports (pjax.min.js:1:9364)
(匿名)	@	VM347:10
(匿名)	@	VM347:21
module.exports	@	pjax.min.js:1
(匿名)	@	pjax.min.js:1
module.exports	@	pjax.min.js:1
module.exports	@	pjax.min.js:1
(匿名)	@	pjax.min.js:1
module.exports	@	pjax.min.js:1
(匿名)	@	pjax.min.js:1
afterAllSwitches	@	pjax.min.js:1
onSwitch	@	pjax.min.js:1
outerHTML	@	pjax.min.js:1
(匿名)	@	pjax.min.js:1
module.exports	@	pjax.min.js:1
switchSelectors	@	pjax.min.js:1
loadContent	@	pjax.min.js:1
module.exports	@	pjax.min.js:1
pjax.handleResponse	@	(索引):800
request.onreadystatechange	@	pjax.min.js:1
XMLHttpRequest.send		
module.exports	@	pjax.min.js:1
loadUrl	@	pjax.min.js:1
linkAction	@	pjax.min.js:1
(匿名)	@	pjax.min.js:1
```
需要继续定位确认

**Comment by wjy2018** [comment]
> 第一次点进来之后没有gitalk评论模块，报错如下：
> 
> ```
> VM347:10  Uncaught ReferenceError: Gitalk is not defined  
>     at <anonymous>:10:24  
>     at <anonymous>:21:7  
>     at module.exports (pjax.min.js:1:7651)
>     at pjax.min.js:1:9113
>     at NodeList.forEach (<anonymous>)
>     at module.exports (pjax.min.js:1:9364)
>     at module.exports (pjax.min.js:1:8931)
>     at pjax.min.js:1:4649
>     at NodeList.forEach (<anonymous>)
>     at module.exports (pjax.min.js:1:9364)
> (匿名)	@	VM347:10
> (匿名)	@	VM347:21
> module.exports	@	pjax.min.js:1
> (匿名)	@	pjax.min.js:1
> module.exports	@	pjax.min.js:1
> module.exports	@	pjax.min.js:1
> (匿名)	@	pjax.min.js:1
> module.exports	@	pjax.min.js:1
> (匿名)	@	pjax.min.js:1
> afterAllSwitches	@	pjax.min.js:1
> onSwitch	@	pjax.min.js:1
> outerHTML	@	pjax.min.js:1
> (匿名)	@	pjax.min.js:1
> module.exports	@	pjax.min.js:1
> switchSelectors	@	pjax.min.js:1
> loadContent	@	pjax.min.js:1
> module.exports	@	pjax.min.js:1
> pjax.handleResponse	@	(索引):800
> request.onreadystatechange	@	pjax.min.js:1
> XMLHttpRequest.send		
> module.exports	@	pjax.min.js:1
> loadUrl	@	pjax.min.js:1
> linkAction	@	pjax.min.js:1
> (匿名)	@	pjax.min.js:1
> ```
> 
> 需要继续定位确认

此问题已通过重新修改pjax适配方式解决
